name: Automagically accept repo invites to this account

on:
  # Always re-run to test lastest changes
  push:
    branches:
    - main
  schedule:
    # Check at the 0th minute every hour
    - cron: '0 * * * *'
    # Check every 15 minutes during active hours, GMT+800 timezone.
    - cron: '15-45/15 0-15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true  # allowed to fail silently
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Run automation script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SEARCH_URL: ${{ secrets.SEARCH_URL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
      run: python3 ./run.py